# Generated by Django 3.0.4 on 2020-03-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='animalbreed',
            constraint=models.CheckConstraint(check=models.Q(eating_type__in=[('ALL', 'All'), ('Plants', 'Plants'), ('Meat', 'Meat')]), name='eating_type_valid'),
        ),
    ]
