# Generated by Django 3.0.4 on 2020-03-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200327_1857'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='animalbreed',
            name='eating_type_valid',
        ),
    ]
